// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfpfGVFN0R_8pS1usGyrxRiw294lWLWHg',
    appId: '1:924357357670:web:4d24b89a1f38c50a663da7',
    messagingSenderId: '924357357670',
    projectId: 'fir-teste-9145d',
    authDomain: 'fir-teste-9145d.firebaseapp.com',
    storageBucket: 'fir-teste-9145d.appspot.com',
    measurementId: 'G-4RGWSY1685',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiePhK58oNxoi4A4sXYPo3ESmF8ifAD9E',
    appId: '1:924357357670:android:e5f6589a9fda44be663da7',
    messagingSenderId: '924357357670',
    projectId: 'fir-teste-9145d',
    storageBucket: 'fir-teste-9145d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKKavgWf1wS6993O0eB1MP6xfJUAm0UrA',
    appId: '1:924357357670:ios:f8e05544c1be58e7663da7',
    messagingSenderId: '924357357670',
    projectId: 'fir-teste-9145d',
    storageBucket: 'fir-teste-9145d.appspot.com',
    iosBundleId: 'com.example.aula1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKKavgWf1wS6993O0eB1MP6xfJUAm0UrA',
    appId: '1:924357357670:ios:f8e05544c1be58e7663da7',
    messagingSenderId: '924357357670',
    projectId: 'fir-teste-9145d',
    storageBucket: 'fir-teste-9145d.appspot.com',
    iosBundleId: 'com.example.aula1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfpfGVFN0R_8pS1usGyrxRiw294lWLWHg',
    appId: '1:924357357670:web:5136de817803b4cc663da7',
    messagingSenderId: '924357357670',
    projectId: 'fir-teste-9145d',
    authDomain: 'fir-teste-9145d.firebaseapp.com',
    storageBucket: 'fir-teste-9145d.appspot.com',
    measurementId: 'G-1075R9P7BW',
  );

}